### PR TITLE
feat(deque#rotate): Add rotate method to Immutable::Deque

### PR DESCRIPTION
**Pull request by ted-hanson**
* brings in-line with modern Deque libs
* allow for more efficient rotation than Array#rotate
* adds rspec tests for new functionality

### CODE REVIEW

**Comment by alexdowad** [comment]
Looks great! Applied to master with adjusted comment ('rotation' not
'rotatation', etc) and commit message. Thanks very much for this
contribution.

If you are interested in doing more, here are some ideas:

   - I am wondering if a more efficient implementation is possible. At
   least, we could cast out multiples of `self.size` from the rotation
   distance. I am guessing there is more than that which could also be done.
   - If you do try for a more efficient implementation, note that the code
   for a left rotation can also be used for a right rotation; just reverse
   `@left` and `@right` within the code.

Please let me know if you plan to make more contributions; when you are
done, I will cut a new version of the gem.

**Comment by ted-hanson** [comment]
@alexdowad i can definitely look into a more performant algorithm.  I'll run with your current ideas and see if I can whip anything up. 

Good fixes on the typos sorry I was just trying to hack something together for an adventofcode problem :P

**Comment by alexdowad** [comment]
Just pushed a more performant version to 'master'. The code is almost
unreadable, but it knocks 40% off the runtime of your (beautiful and
readable) version.

**Comment by ted-hanson** [comment]
nice! great work :) The %= is probably a big gain in perf but will definitely check it out!

**Pull request closed without merging**
